BattleshipGame: battleship.o driver.o ai.o
	 g++ -o BattleshipGame battleship.o driver.o ai.o

battleship.o: battleship.cpp battleship.h
	g++ -c battleship.cpp

driver.o: driver.cpp
	g++ -c driver.cpp

ai.o: ai.cpp
	g++ -c ai.cpp
